import type { ChronologieLandingData } from '@/types/chronologie'

export const chronologieHome: ChronologieLandingData = {
  brand: 'Chronologie',
  navigation: [
    { label: 'HOME', href: '#top' },
    { label: 'COLLECTION', href: '#collection' },
    { label: 'JOURNAL', href: '#journal' },
    { label: 'ABOUT', href: '#about' },
    { label: 'CONTACT', href: '#contact' },
  ],
  headerAction: { label: 'VISIT THE STORE', href: '#boutique' },
  intro: {
    eyebrow: '',
    title: '',
    description: '',
  },
  boutique: {
    overline: '',
    title: '',
    description: '',
    detail: '',
  },
  story: {
    eyebrow: '',
    title: '',
    paragraphs: [],
  },
  values: {
    eyebrow: '',
    vision: {
      title: '',
      description: '',
    },
    mission: {
      title: '',
      description: '',
    },
  },
  service: {
    eyebrow: '',
    title: '',
    description: '',
    action: { label: '', href: '#' },
    items: [],
    notes: [],
  },
  hero: {
    title: 'Time, considered\nwith intention.',
    description: 'A private atelier of rare and pre-owned timepieces from the world\'s most respected maisons.',
    image: '/chronologie/2455bad675dd79221da8d333a49557065868287e.png',
    primaryAction: { label: 'INQUIRE VIA WHATSAPP', href: '#contact-cta' },
    secondaryAction: { label: 'EXPLORE COLLECTION', href: '#collection' },
  },
  collection: {
    eyebrow: 'SELECTED PIECES',
    title: 'A curated selection of exceptional timepieces',
    description: 'Timeless craftsmanship. Iconic design.\nChosen for those who value every second.',
    categories: [],
    items: [
      {
        brand: 'Rolex',
        name: 'Submariner\nNo-Date',
        summary: 'A study in restraint and precision',
        cta: 'INQUIRE VIA WHATSAPP',
        tone: 'charcoal',
        size: 'hero',
        image: '/chronologie/db1569cafa99fae6f9e92d47dab874f7cfcb8061.png',
      },
      {
        brand: 'PATEK PHILIPPE',
        name: 'Ref. 5172G',
        summary: '',
        cta: 'INQUIRE',
        tone: 'gold',
        size: 'tall',
        image: '/chronologie/84ed0f660160bebd62bde1bf021afa5d51de56d3.png',
      },
      {
        brand: 'Rolex',
        name: 'Cosmograph\nDaytona',
        summary: '',
        cta: 'INQUIRE',
        tone: 'charcoal',
        size: 'tall',
        image: '/chronologie/f1f33106cda819f72012300bd50deccac173c360.png',
      },
      {
        brand: 'PATEK PHILIPPE',
        name: 'Calatrava\nUltra-Thin',
        summary: '',
        cta: 'INQUIRE',
        tone: 'sand',
        size: 'wide',
        image: '/chronologie/3696da8db57ccc52c4891f3abf2d9524f51bbcb4.png',
      },
      {
        brand: 'Rolex',
        name: 'Datejust 36',
        summary: '',
        cta: 'INQUIRE',
        tone: 'ivory',
        size: 'wide',
        image: '/chronologie/19d1315286fbf632376a74a63367d4a3604b1812.png',
      },
      {
        brand: 'AUDEMARS PIGUET',
        name: 'Royal Oak',
        summary: '',
        cta: 'INQUIRE',
        tone: 'steel',
        size: 'wide',
        image: '/chronologie/3ab3dd52e459dc6dbd1da84f746a3a1451251743.png',
      },
    ],
    action: { label: 'VIEW ALL TIMEPIECES', href: '#collection' },
  },
  craft: {
    eyebrow: 'OUR PHILOSOPHY',
    title: 'We do not sell watches.\nWe curate them.',
    description:
      'Chronologie was founded on a simple conviction — that a fine timepiece deserves more than a transaction. It deserves a conversation.\n\nEach watch in our atelier is selected by hand, authenticated by experts, and presented in a setting that honours its provenance. We invite you to discover ours.',
    image: '/chronologie/5c0822818f1e64ed319d82e9575a81ef17b3c5d3.png',
    action: { label: 'OUR STORY', href: '#about' },
  },
  invitation: {
    eyebrow: 'THE BOUTIQUE',
    title: 'An invitation to spend time with time.',
    description:
      'Our Jakarta showroom is a quiet space — by appointment, by candlelight, by conversation. We look forward to receiving you.',
    image: '/chronologie/3c392a3f7b186b0e6024b48034095786181601e8.png',
    action: { label: 'BOOK A PRIVATE VIEWING', href: '#contact-cta' },
  },
  journal: {
    eyebrow: 'JOURNAL',
    title: 'Insights on time, craftsmanship, and collecting',
    description: 'Stories and perspectives from the world of fine watchmaking.',
    featured: {
      category: 'COLLECTING',
      date: 'APRIL 21, 2026',
      title: 'The Art of Collecting Vintage Rolex',
      excerpt: 'Understanding the value beyond time: What makes a vintage Rolex more than just a watch...',
      href: '#journal',
      tone: 'vintage',
      image: '/chronologie/0ad896858e1a105287b036d199b445a5a5d5c60f.png',
    },
    secondary: [
      {
        category: 'CRAFTSMANSHIP',
        date: 'APRIL 18, 2026',
        title: 'Inside Patek Philippe Craftsmanship',
        excerpt: 'A legacy of precision passed down through generations. Discover the meticulous artistry behind every timepiece...',
        href: '#journal',
        tone: 'craft',
        image: '/chronologie/629d0802680ef9f0a6015e28760e70e5b2c4af1e.png',
      },
      {
        category: 'PERSPECTIVE',
        date: 'APRIL 15, 2026',
        title: 'What Defines a Modern Luxury Watch',
        excerpt: 'Beyond aesthetics: the details, engineering, and heritage that shape a true modern icon...',
        href: '#journal',
        tone: 'modern',
        image: '/chronologie/47f30ab8742ea3787271f936540a5ac1b23dd51a.png',
      },
    ],
  },
  contactCta: {
    title: 'Begin a quiet conversation.',
    description:
      'Whether seeking your first timepiece or expanding a thoughtful collection — we are here to listen.',
    primaryAction: { label: 'INQUIRE VIA WHATSAPP', href: '#contact' },
    secondaryAction: { label: 'VISIT THE BOUTIQUE', href: '#boutique' },
  },
  footer: {
    description: 'A curated atelier of fine timepieces. By appointment, by passion, by tradition.',
    columns: [
      {
        title: 'DISCOVER',
        items: [
          { label: 'Collection', href: '#collection' },
          { label: 'Maisons', href: '#collection' },
          { label: 'Journal', href: '#journal' },
          { label: 'About', href: '#about' },
        ],
      },
      {
        title: 'BOUTIQUE',
        items: [
          { label: 'Plaza Indonesia, Level 2', href: '#boutique' },
          { label: 'Jl. M.H. Thamrin Kav. 28–30', href: '#boutique' },
          { label: 'Jakarta Pusat 10350', href: '#boutique' },
          { label: 'Indonesia', href: '#boutique' },
        ],
      },
      {
        title: 'CONTACT',
        items: [
          { label: '+62 812 3456 7890', href: 'tel:+6281234567890' },
          { label: 'concierge@chronologie.id', href: 'mailto:concierge@chronologie.id' },
        ],
      },
    ],
    legalLeft: '© 2026 Chronologie. All rights reserved.',
    legalRight: 'Authorised Pre-Owned Specialists',
  },
}
